require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/media_flows", type: :request do
  
  # MediaFlow. As you add validations to MediaFlow, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MediaFlow.create! valid_attributes
      get media_flows_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      media_flow = MediaFlow.create! valid_attributes
      get media_flow_url(media_flow)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_media_flow_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      media_flow = MediaFlow.create! valid_attributes
      get edit_media_flow_url(media_flow)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MediaFlow" do
        expect {
          post media_flows_url, params: { media_flow: valid_attributes }
        }.to change(MediaFlow, :count).by(1)
      end

      it "redirects to the created media_flow" do
        post media_flows_url, params: { media_flow: valid_attributes }
        expect(response).to redirect_to(media_flow_url(MediaFlow.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MediaFlow" do
        expect {
          post media_flows_url, params: { media_flow: invalid_attributes }
        }.to change(MediaFlow, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post media_flows_url, params: { media_flow: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested media_flow" do
        media_flow = MediaFlow.create! valid_attributes
        patch media_flow_url(media_flow), params: { media_flow: new_attributes }
        media_flow.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the media_flow" do
        media_flow = MediaFlow.create! valid_attributes
        patch media_flow_url(media_flow), params: { media_flow: new_attributes }
        media_flow.reload
        expect(response).to redirect_to(media_flow_url(media_flow))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        media_flow = MediaFlow.create! valid_attributes
        patch media_flow_url(media_flow), params: { media_flow: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested media_flow" do
      media_flow = MediaFlow.create! valid_attributes
      expect {
        delete media_flow_url(media_flow)
      }.to change(MediaFlow, :count).by(-1)
    end

    it "redirects to the media_flows list" do
      media_flow = MediaFlow.create! valid_attributes
      delete media_flow_url(media_flow)
      expect(response).to redirect_to(media_flows_url)
    end
  end
end
